-- MIGRATION_0001: Schema inicial
-- Descrição: Criação das tabelas base (orgs, profiles, memberships, audit_log)

-- CREATE TABLE orgs ...
-- CREATE TABLE profiles ...
-- CREATE TABLE memberships ...
-- CREATE TABLE audit_log ...
